name: Copy tools.js to docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  copy-tools:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy tools.js to docs/
        run: |
          cp tools.js docs/tools.js

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/tools.js
          git commit -m "Copy tools.js to docs/" || echo "No changes to commit"
          git push || echo "Nothing to push"
